php_myclass.lo: /zodb/phpzope/phpexample/example/php_myclass.cpp
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/zodb/phpzope/phpexample/example $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /zodb/phpzope/phpexample/example/php_myclass.cpp -o php_myclass.lo 
$(phplibdir)/myclass.la: ./myclass.la
	$(LIBTOOL) --mode=install cp ./myclass.la $(phplibdir)

./myclass.la: $(shared_objects_myclass) $(MYCLASS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_myclass) $(MYCLASS_SHARED_LIBADD)

